- name: install cart module
  hosts: cart
  become: true
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present

    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download application code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: unzip file roboshop-artifacts
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: install npm dependencies
      community.general.npm:
        path: /app

    - name: copy cart service to system module
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable cart and start
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes
