- name: install module catalogue
  hosts: catalogue
  become: yes
  tasks:
    - name: disable nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: create system usee
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download roboshop-artifacts
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    # this  module thinks  file exist  on ansible  control  server, needs to extract on to remote machine
    # remote_src --> means file already exist in catalogue server
    - name: unarchive the file
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: download nodejs using NPM
      community.general.npm:
        path: /app

    - name: copy catalogue service to system module
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
        remote_src: yes

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable catalogue and start
      ansible.builtin.service:
        name: catalogue
        state: started
        enabled: yes

    - name: copy mongoDB repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongoDB client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present

    - name: check the data is loaded are not
      ansible.builtin.command: mongosh --host mongodb.nagendrablog.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: printing the catalogue_output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: load product
      ansible.builtin.shell: mongosh --host mongodb.nagendrablog.site </app/db/master-data.js
      when: catalogue_output.stdout | int < 0
