- name: configure the dispatch
  hosts: dispatch
  become: yes

  tasks:
    - name: install golang
      ansible.builtin.dnf:
        name: golang
        state: present

    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download roboshop-artifacts
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
        dest: /tmp/dispatch.zip

    - name: unarchive dispatch code
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: yes

    # very important – idempotent go mod init
    - name: go mod init only if not exists
      ansible.builtin.command: go mod init dispatch
      args:
        chdir: /app
        creates: /app/go.mod

    - name: go mod tidy
      ansible.builtin.command: go mod tidy
      args:
        chdir: /app

    - name: go build
      ansible.builtin.command: go build
      args:
        chdir: /app

    - name: copy dispatch service to systemd
      ansible.builtin.copy:
        src: dispatch.service
        dest: /etc/systemd/system/dispatch.service

    - name: daemon-reload systemd
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable dispatch and start
      ansible.builtin.service:
        name: dispatch
        state: started
        enabled: true
