- name: configure the dispatch
  hosts: dispatch
  become: yes
  tasks:
    - name: install golang
      ansible.builtin.dnf:
        name: golang
        state: installed

    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download roboshop-artifacts
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip
        dest: /tmp/dispatch.zip

    # this  module thinks  file exist  on ansible  control  server, needs to extract on to remote machine
    # remote_src --> means file already exist in catalogue server
    - name: unarchive the file
      ansible.builtin.unarchive:
        src: /tmp/dispatch.zip
        dest: /app
        remote_src: yes

    - name: run go build steps
      ansible.builtin.command: "{{ item }}"
      args:
        chdir: /app
      loop:
        - "go mod init dispatch"
        - "go mod tidy"
        - "go build"

    - name: copy catalogue service to system module
      ansible.builtin.copy:
        src: dispatch.service
        dest: /etc/systemd/system/dispatch.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable dispatch and start
      ansible.builtin.service:
        name: dispatch
        state: started
        enabled: true
