- name: create rabbitmq and copy the repo
  hosts: rabbitmq
  become: yes

  tasks:
    - name: copy rabbitmq repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq server
      ansible.builtin.dnf:
        name: rabbitmq-server
        state: present

    - name: enable and start rabbitmq-server service
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: true

    - name: create rabbitmq user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        permissions:
          - vhost: /
            configure_priv: .*
            read_priv: .*
            write_priv: .*
        state: present
