- name: create rabbitmq and copy the repo
  hosts: rabbitmq
  become: yes
  tasks:
    - name: copy the rabbitmq repo
      ansible.builtin.copy:
        src: rabbitmq.repo
        dest: /etc/yum.repos.d/rabbitmq.repo

    - name: install rabbitmq server
      ansible.builtin.command: dnf install rabbitmq-server -y

    - name: enable and start rabbitmq
      ansible.builtin.service:
        name: rabbitmq
        state: started
        enabled: yes

    - name: creating new user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
