- name: create shipping module
  hosts: shipping
  become: yes
  tasks:
    - name: install maveen
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download shipping artifact
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unarchive the shipping file
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: clean package
      ansible.builtin.command: mvn clean package
      args:
      chdir: /app

    - name: move shipping jar file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app

    - name: copy shipping service to system module
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable shipping and start
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: yes
