- name: create shipping module
  hosts: shipping
  become: yes

  tasks:
    - name: install maven and mysql client
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - maven
        - mysql

    - name: create system user
      ansible.builtin.user:
        name: roboshop
        shell: /sbin/nologin
        home: /app
        system: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download shipping artifact
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /tmp/shipping.zip

    - name: unarchive the shipping file (idempotent)
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes
        creates: /app/pom.xml

    - name: clean package only if JAR not built
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app
        creates: /app/target/shipping-1.0.jar

    - name: move shipping jar file only if not renamed
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app
        creates: /app/shipping.jar

    - name: copy shipping service to system module
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: daemon-reload
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: enable shipping and start
      ansible.builtin.service:
        name: shipping
        state: started
        enabled: true

    - name: install python mysql dependency for ansible
      ansible.builtin.pip:
        name: PyMySQL

    - name: import data
      tags: [import]
      community.mysql.mysql_db:
        name: all
        login_user: root
        login_password: RoboShop@1
        login_host: mysql.sh.nagendrablog.site
        state: import
        target: "{{ item }}"
      loop:
        - /app/db/schema.sql
        - /app/db/app-user.sql
        - /app/db/master-data.sql

    - name: restart shipping
      tags: [import]
      ansible.builtin.service:
        state: restarted
        name: shipping
